swagger: "2.0"
info:
  title: Forum
  version: "0.1"
  description: Forum - API

produces: ["application/json"]

basePath: /api/v1

tags:
  - name: Post

paths:

  #==================================================[Path]
  "/posts":
    get:
      tags: [Post]
      operationId: getPosts
      security:
      - userAuth: []
      parameters:
      - $ref: "#/parameters/PageQueryParameter"
      - $ref: "#/parameters/SizeQueryParameter"
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              "$ref": "#/definitions/PostModel"
        "401":
          "$ref": "#/responses/Unauthorized"
    post:
      tags: [Post]
      operationId: createPost
      security:
        - userAuth: []
      consumes:
        - application/json
      parameters:
        - in: body
          name: postModel
          required: true
          schema:
            "$ref": "#/definitions/PostModel"
      responses:
        "201":
          description: Created
          schema:
            "$ref": "#/definitions/PostModel"
        "400":
          "$ref": "#/responses/BadRequest"
        "401":
          "$ref": "#/responses/Unauthorized"
        "403":
          "$ref": "#/responses/Forbidden"

  "/posts/{postId}":
    parameters:
      - name: postId
        in: path
        required: true
        type: string
        format: uuid
    get:
      tags: [Post]
      operationId: getPost
      security:
      - userAuth: []
      responses:
        "200":
          description: OK
          schema:
            "$ref": "#/definitions/PostModel"
        "400":
          "$ref": "#/responses/BadRequest"
        "401":
          "$ref": "#/responses/Unauthorized"
        "403":
          "$ref": "#/responses/Forbidden"
        "404":
          "$ref": "#/responses/NotFound"
    delete:
      tags: [Post]
      operationId: deletePost
      security:
        - userAuth: []
      responses:
        "204":
          description: No Content
        "400":
          "$ref": "#/responses/BadRequest"
        "401":
          "$ref": "#/responses/Unauthorized"
        "403":
          "$ref": "#/responses/Forbidden"
definitions:

  PostModel:
    type: object
    required:
      - title
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      title:
        type: string
      content:
        type: string
      imageUrl:
        type: string

  Problem:
    type: object
    properties:
      type:
        type: string
        format: uri
      title:
        type: string
      status:
        type: integer
        format: int32
        minimum: 100
        maximum: 600
      detail:
        type: string
      instance:
        type: string
        format: uri
      violations:
        type: array
        items:
          $ref: "#/definitions/Violation"

  Violation:
    type: object
    properties:
      field:
        type: string
      message:
        type: string



parameters:
  PageQueryParameter:
    name: page
    in: query
    type: integer
    default: 1
    minimum: 1

  SizeQueryParameter:
    name: size
    in: query
    type: integer
    default: 10
    minimum: 10
    maximum: 30

responses:

  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Problem"
  BadRequest:
    description: Bad Request
    schema:
      $ref: "#/definitions/Problem"
  Forbidden:
    description: Forbidden
    schema:
      $ref: "#/definitions/Problem"
  NotFound:
    description: Not Found
    schema:
      $ref: "#/definitions/Problem"