---
app:
  dir:
    upload-dir: "${APP_DIR_UPLOAD_DIR}"
  jwt:
    base64-secret: "${APP_JWT_BASE64_SECRET:}"
    access-token-validity: "3600" # 1 hour in seconds
    refresh-token-validity: "31536000" # year in seconds

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SPRING_DATASOURCE_URL:}"
    username: "${SPRING_DATASOURCE_USERNAME:}"
    password: "${SPRING_DATASOURCE_PASSWORD:}"
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    default-property-inclusion: non_null

server:
  port: "${PORT:8080}"

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 1MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: forum
    password: forum
    url: jdbc:postgresql://localhost:5432/forum_db
  flyway:
    baseline-on-migrate: true

---

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 1MB
  flyway:
    baseline-on-migrate: true

---

app:
  dir:
    upload-dir: "src/main/resources/"
  jwt:
    base64-secret: "dvkfGCq2G00TFJ3j+4UDS+CPwAVLkLziJXlXUvNy2jr0NkIH4QPtfXOLpHK1G++RixsyY5CX6BRh82lZySF4Xg=="