---
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 1MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: forum
    password: forum
    url: jdbc:postgresql://localhost:5432/forum_db
  flyway:
    baseline-on-migrate: true